### ISSUE TITLE
Supporting NFT thumbnails @ guild profiles

### ISSUE THREAD

**Issue by streamerd** [agoraxyz/guild.xyz#230]
hello,

would be cool to include image thumbnail and price of those tokens or collections.

such metadata could be displayed somewhere near those card items:

![](https://i.imgur.com/3OpUxua.png)

**Comment by Brunya** [comment]
Good idea. Submit it to our community driven roadmap:
https://roadmap.guild.xyz/b/feature-requests/

**Comment by streamerd** [comment]
just did so, yeah and realised it'd be making it easier to differentiate between when multiple NFTs exist like that^
