### ISSUE TITLE
Use our @guildxyz/sdk instead of custom abstractions

### ISSUE THREAD

**Issue by dovalid** [agoraxyz/guild.xyz#296]

**Comment by BrickheadJohnny** [comment]
## TODO list

Replace `fetcher` function calls with Guild SDK functions in the following components/hooks:
- [ ] index.tsx
- [ ] linkpreview.tsx
- [ ] [guild]/index.tsx
- [ ] [guild]/linkpreview.tsx
- [ ] useCreateGuild
- [ ] useEditGuild
- [ ] useDeleteGuild
- [ ] useCreateRole
- [ ] useEditRole
- [ ] useDeleteRole
- [ ] useJoinPlatform
- [ ] useLeaveGuild
- [ ] useUpdateUser
- [ ] sitemap
