### ISSUE TITLE
EIP-1271 support

### ISSUE THREAD

**Issue by arddluma** [agoraxyz/guild.xyz#317]
Hi there,
I am getting `Invalid digital signature!` using smart contract based wallet.
Do you guys have any plans to support EIP-1271 ?
Thanks!

**Comment by D3vl0per** [comment]
Hi @arddluma,
Feel free to DM me or other Community Manager in our Discord Guild to investigate your problem.
The next generation signing procedure is currently being planned and under R&D. We chose EIP-712, but this proposal is still in the review stage and incompatibility issues may arise.
So, yes, we have a plain to utilize EIP-712.

**Comment by cs-balazs** [comment]
Closing this, as we now support EIP-1271
