### ISSUE TITLE
Guild Guard: "Keep access for existing users" description is confusing

### ISSUE THREAD

**Issue by with-heart** [agoraxyz/guild.xyz#346]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/1954752/166160463-79909ed3-b5e1-47ef-890c-1b91f5eb457c.png">

```
There are 0 members without any role, if you want them to auto-access too, give them a role!
```

Just wanted to report this as a potential place for the UI to be more clear for users. This sentence feels difficult to parse which leaves me feeling like I'm not even sure what it means.

**Comment by dovalid** [comment]
Thank you @with-heart, very much agreed! We wanted to express a "give roleless members manually a random role before you turn this on if you want to keep their access" manual here very briefly but it wasn't a realistic usecase anyway, eventually we'll evolve the option to really keep access of all members, regardless if they have a role or not. So removed the confusing instruction and made the description more explicit in b8c7ba4bc8aafe949714ac3b0aeb7e4ab8b92968

**Comment by with-heart** [comment]
Thanks @dovalid! Appreciate the context! Love the change in wording, answers the question I had when I was in that situation ♥️
