### ISSUE TITLE
no admin status on discord server recognised 

### ISSUE THREAD

**Issue by NiklasTR** [agoraxyz/guild.xyz#348]
![image](https://user-images.githubusercontent.com/18559148/166698321-69c0dc97-771b-4cae-96b3-bb3c1cb959dc.png)

Hi guild team - it seems like even after re-signing with my metamask, and checking that my discord account is recognized, I can not set up a new guild. Is there a common error on my side thatäs responsible for this? 

Best, Niklas

**Comment by BrickheadJohnny** [comment]
Hello @NiklasTR, sorry for not responding to this in time. I believe this issue is solved since then, so closing it now.
