### ISSUE TITLE
 Cannot read properties of undefined (reading 'includes') while creating Role

### ISSUE THREAD

**Issue by juniormp** [agoraxyz/guild.xyz#365]
I am trying to create a Role through guildxyz sdk and I am receiving this error message:  ` Cannot read properties of undefined (reading 'includes') when creating Role`.

The response throws an exception but the Role itself is created (I checked in the web app).

I have tried to create the role through the web app and the same error occurs.

![image](https://user-images.githubusercontent.com/5060670/169541476-8df8ff1d-e610-41e9-bbad-90515d60f356.png)

**Comment by BrickheadJohnny** [comment]
Hey @juniormp , thank you for the bug report! This was an issue with our API and we've just deployed a hotfix for it, so it should work properly now. Let us know if you run into any other issues!
