### ISSUE TITLE
Wrong response code

### ISSUE THREAD

**Issue by gitaalekhyapaul** [agoraxyz/guild.xyz#610]
Please change the response code to `405: Method Not Allowed` since it is not a server error, rather than a user error and thus 5xx series codes must not be used, instead use the 4xx series codes for client errors.

https://github.com/agoraxyz/guild.xyz/blob/f23a6291215e4347d73cfd60f315cb33b2be2ed8/src/pages/api/poap/index.ts#L8

**Comment by BrickheadJohnny** [comment]
Hello @gitaalekhyapaul, thank you so much for the suggestion, I just changed it and all its occurrences (923ec7a615677196da2a9807f0f320dc8a50bc2e)
