### ISSUE TITLE
Users are getting stuck when using MetaMask browser on mobile and Discord

### ISSUE THREAD

**Issue by olivierlesnicki** [agoraxyz/guild.xyz#649]
After connecting their wallets to guild.xyz using MetaMask browser on mobile, users attempt to login with Discord. After confirming the permissions, they're being redirected to a page that reads "You're being redirected... Closing the authentication window and taking you back to the site..."

![IMG_6419 (1)](https://user-images.githubusercontent.com/1705944/212474795-c342a3c3-41ea-43fd-8e56-88863f052855.png)

**Comment by BrickheadJohnny** [comment]
Hello, we've completely reworked the auth flow, so users shouldn't experience this issue now. Thanks for your report!
