### ISSUE TITLE
Multi wallet - Requirement

### ISSUE THREAD

**Issue by quentingosset** [agoraxyz/guild.xyz#697]
Is it possible to add the possibility that the requirements are validated if we have several wallets connected? 
In my example, all my 2 wallets are 2000 PLU which makes me eligible for the role, but currently I'm told I don't follow it.

![image](https://user-images.githubusercontent.com/6824137/219746703-9f1db7a5-4d00-46f1-bd7b-95810833d3d4.png)

**Comment by BrickheadJohnny** [comment]
Hello @quentingosset, closing this issue, we'll get back to you ASAP on Intercom.
