### ISSUE TITLE
Authentication Aware Header Proposal

### ISSUE THREAD

**Issue by D3vl0per** [agoraxyz/guild.xyz#724]
This header is added to the request in case the frontend either signs the request via the user's browser-integrated wallet or via the browser's crypto API, which goes to the Guild's backend API. 
The feature is that an intermediate dedicated microservice will process the digital signature verification for these requests in the future. 
It makes sense for this service to process requests endpoint independently, i.e. it does not need to know which endpoints require authentication. This way it is unnecessary to parse the HTTP body of each request and decide whether it is an authenticated request.
Example:
`x-guild-auth: 1`

**Comment by cs-balazs** [comment]
Since our auth endpoints can now accept params in both the header, and the body of the request, wouldn't it be useful for the service if this indicated where the parameters (and the signature) are located?
`x-guild-auth: body`
`x-guild-auth: header`

We could even name it `x-guild-auth-location` to make it more descriptive

**Comment by D3vl0per** [comment]
I support the `x-guild-auth-location` header name, I think it's ideal in the case you outlined.

**Comment by D3vl0per** [comment]
> Since our auth endpoints can now accept params in both the header, and the body of the request, wouldn't it be useful for the service if this indicated where the parameters (and the signature) are located? `x-guild-auth: body` `x-guild-auth: header`
> 
> We could even name it `x-guild-auth-location` to make it more descriptive @D3vl0per

I support the `x-guild-auth-location` header name, I think it's ideal in the case you outlined.
