### ISSUE TITLE
Unable to connect twitter (error: rate.limited)

### ISSUE THREAD

**Issue by 6102yk** [agoraxyz/guild.xyz#757]
Got this error (top right corner) when reconnecting Twitter.
![msedge_dF0kdNUNTL](https://user-images.githubusercontent.com/64273497/229334212-70c62ed5-9f66-49cd-af78-c1226ddf0cfe.png)

I tried revoking the connection on Twitter and reconnecting it after this error happened. But now it said "Auth needed to check access". 
![image](https://user-images.githubusercontent.com/64273497/229334269-13c5d946-a3ed-44ba-9b31-169f45b8c5a5.png)

**Comment by BrickheadJohnny** [comment]
Hello, there isn't a "fix" for issues like this (rate limit), so please try again later - it should work as expected.

**Comment by royalventure** [comment]
I meet this error today,
still not helped
