### ISSUE TITLE
Unable to connect to Twitter - blocked by CORS policy

### ISSUE THREAD

**Issue by boquetmathieu** [agoraxyz/guild.xyz#758]
I have this issue when I try to connect to Twitter:

`Access to fetch at 'https://api.guild.xyz/v1/user/connect' from origin 'https://guild.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by BrickheadJohnny** [comment]
Hello, we've fixed this issue a couple of weeks ago, so it should work properly now.
