### ISSUE TITLE
Wallet Connect fails to check wallet after signature: CORS 

### ISSUE THREAD

**Issue by maplesyrupsucker** [agoraxyz/guild.xyz#810]
When connected via wallet connect on mobile or desktop, the website fails to check wallet after wallet completes signature event. 

Appears console logs are throwing errors related to CORS

```
to load resource: the server responded with a status of 429 ()
verse:1 Access to fetch at 'https://api.athens2.zetachain.com/evm' from origin 'https://guild.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
api.athens2.zetachain.com/evm:1     Failed to load resource: net::ERR_FAILED
```

**Steps to reproduce:** 

1. Connect to guild.xyz via wallet connect
2. Sign message in wallet wallet
3. Green button stays in permanent "Check your wallet" spinning ajax wheel 
4. Console errors show message below related to CORS issue

<img width="1236" alt="image" src="https://github.com/agoraxyz/guild.xyz/assets/3764321/2284fee1-e4f8-4915-a61f-7002f51076b6">

Also just a friendly reminder that Wallet Connect V1 is being sunset in near future for V2

**Comment by BrickheadJohnny** [comment]
Hello @maplesyrupsucker, thank you for the report. The issue wasn't on our side, but in the meantime we've added WalletConnect V2 support, so could you please try connecting with it? We'll remove WalletConnect V1 from Guild once it'll be officially deprecated. Thank you so much for the heads up regarding this!
