### ISSUE TITLE
No access to join linea guild

### ISSUE THREAD

**Issue by Modric4** [agoraxyz/guild.xyz#832]
![Screenshot_20230614-230700](https://github.com/agoraxyz/guild.xyz/assets/134769678/99a3c1a3-e070-451b-8939-6d3db48b268a)
Have added all social accounts but still saying am not eligible . Please help. My wallet address: 0xFEbB179C176064c1da71cE9081892cCfcA7E51CD

**Comment by BrickheadJohnny** [comment]
Hello, as you can see on the screenshot, you do not satisfy the secret requirements, so you can't join this guild. This isn't an issue, but it's the expected behaviour, so I'm closing it now.
