### ISSUE TITLE
twitter reconnect issue Request failed with status code 403 

### ISSUE THREAD

**Issue by hodifaalquraan** [agoraxyz/guild.xyz#836]

**Comment by fsstoo** [comment]
i can't reconnect to twitter even after authorization

**Comment by Arginata** [comment]
Cant reconnect to twitter please help

**Comment by Vonzai96** [comment]
me too, pls help

**Comment by dovalid** [comment]
We're experiencing Twitter API ratelimit, even though we're already in the highest API tier. We've contacted Twitter support, will let you know once it's solved!

**Comment by ispec83** [comment]
> We're experiencing Twitter API ratelimit, even though we're already in the highest API tier. We've contacted Twitter support, will let you know once it's solved!

Could you advise when problems with diconnecting of social accounts (Twitter and others) will be solved. My account in Twitter ISPEC83 was blocked and deleted. Could you assist with removing my connected Twitter ISPEC83.
My wallet address is 0xA70e9590F890603Fb0955eF18c47E748Ec3ced88

**Comment by pael666** [comment]
my twitter got suspend and i want to change it. but it says temporary disabled

**Comment by sergeybruska** [comment]
Hi guys, I'm getting an error "Error: Temporarily unavailable due to Twitter API issues" when I try to join a guild.

**Comment by zionprincess** [comment]
also had this same issue

**Comment by dovalid** [comment]
> Could you advise when problems with diconnecting of social accounts (Twitter and others) will be solved. My account in Twitter ISPEC83 was blocked and deleted. Could you assist with removing my connected Twitter ISPEC83. My wallet address is 0xA70e9590F890603Fb0955eF18c47E748Ec3ced88

Hey, disconnecting social accounts is available again! Please see in the account modal
