### ISSUE TITLE
Twitter reconnect issues and status 400 error while trying to join Linea guild 

### ISSUE THREAD

**Issue by robberdom** [agoraxyz/guild.xyz#837]
I'm having issues connecting my twitter to my wallet and I think it's coz I previously connected a different twitter account which has now been suspended by twitter. I've searched and searched but there's no option to disconnect twitter from my wallet on your site. Can you please help me with this?

My wallet address is 0xD37211a18092ea9Cae29e838844532aD37bE6567

The account I think is connected to it is: robberdom

I could be wrong tho but I think this is the problem, please help me rectify this coz I have to run the Linea task which ends today. Thank you.

**Comment by dovalid** [comment]
Yep, disconnecting social accounts is temporarily disabled. I've removed your connected Twitter manually!
The reconnect might be clunky, as we're experiencing Twitter API ratelimit right now. Please see #836
