### ISSUE TITLE
Github revoked permissions by mistake

### ISSUE THREAD

**Issue by LordJavi** [agoraxyz/guild.xyz#839]
Hi, I connected my github account days ago. By mistake I revoked all permissions in github including guild.xyz 🤦‍♂️ 

![image](https://github.com/agoraxyz/guild.xyz/assets/20624591/561af1ae-95a3-473b-aa62-894383705097)

So today, I was finally able to connect my twitter account successfully but my github account link is broken

![image](https://github.com/agoraxyz/guild.xyz/assets/20624591/727a507e-0bea-405b-943d-78b2e031a775)

and I can't disconnect and reconnect again

![image](https://github.com/agoraxyz/guild.xyz/assets/20624591/d2b08351-eba1-443e-a1de-b6c38f66a3e0)

Can someone help me? my wallet address is 0x5633529553BE9ea0647a3893Ede8A651C384E90a

ty

**Comment by dovalid** [comment]
Hey, thanks for your report! We should display a reconnect button in this case, we'll look into it. Meanwhile I've removed your connected GitHub manually so you can connect again!
