### ISSUE TITLE
can't disconnect social accounts

### ISSUE THREAD

**Issue by dhyanjayalath** [agoraxyz/guild.xyz#840]
### Describe the bug

i can't disconect my social accounts.. the says disconnection temporaly dissabed like that

### To Reproduce

![Base Guild - Google Chrome 6_23_2023 1_34_10 PM](https://github.com/agoraxyz/guild.xyz/assets/137421616/3d0c2a89-71a6-476b-9a8c-468e9039ec74)
like this

### Expected Behavior

i want to disconnect my social accounts

### Which browser are you using? (if relevant)

chrome

**Comment by BrickheadJohnny** [comment]
Hello @dhyanjayalath,
This is not a bug, we've disabled this feature intentionally. We'll need to implement a couple of changes on our backend and once it's ready, we'll enable account disconnection again. Sorry for the inconvenience.
