### ISSUE TITLE
"Next" button remains disabled after installing Discord bot

### ISSUE THREAD

**Issue by aahna-ashina** [agoraxyz/guild.xyz#856]
### Describe the bug

https://guild.xyz/create-guild

### To Reproduce

Go to https://guild.xyz/create-guild and click connect Discord

### Expected Behavior

Discord bot will be correctly installed on Discord server, but the page at https://guild.xyz/create-guild will not update.

![guild_discord](https://github.com/agoraxyz/guild.xyz/assets/95955389/2db8322b-db83-4c2e-84ab-7f72c338809c)

```javascript
GET https://api.guild.xyz/v1/platform/guild/DISCORD/1076036713715089471 404
```

**Comment by BrickheadJohnny** [comment]
Hello @aahna-ashina, our bot actually went offline, probably that's why you had this issue. Thank you for your report, please try again now!
