### ISSUE TITLE
[Bug] WalletConnect connection doesn't persist after a reload

### ISSUE THREAD

**Issue by PetromirDev** [agoraxyz/guild.xyz#857]
### Describe the bug

Connecting to a wallet via WalletConnect works, signing the message after connecting works, but once you refresh you lose your connection on Guild's side. If you try to connect again the WalletConnect button does nothing and you have to clear the dApps's website data in order for it to work again.  

## The wallet (the message was signed in a previous connection)
https://github.com/agoraxyz/guild.xyz/assets/68795596/54e9a390-6901-412d-a04c-4ae4ff620494
## Guild.xyz
https://github.com/agoraxyz/guild.xyz/assets/68795596/e0d63862-2812-4001-8541-79ea929ff8a5

### To Reproduce

Connect to a wallet via WalletConnect and refresh the page.

### Tested on:
- Ambire's desktop wallet
- Zerion's mobile wallet

### Expected Behavior

The connection should persist after refreshing the page and the WalletConnect button should work in case the connection has ended/expired.

**Comment by cs-balazs** [comment]
Thank you for the report, this bug has been fixed in https://github.com/agoraxyz/guild.xyz/commit/f3a2b006019073954e530b5c20b47dc4296aa219
WalletConnect connection now seems to be persistent
