### ISSUE TITLE
Discord roles are not synchronizing with the Guild page

### ISSUE THREAD

**Issue by aahna-ashina** [agoraxyz/guild.xyz#860]
### Describe the bug

When we get access to roles at https://guild.xyz/nation3, the Discord user accounts are not getting updated with their new roles.

Is the Discord<>Guild integration broken?

### To Reproduce

- Go to https://guild.xyz/nation3, join guild, and get role, e.g. (`Genesis Citizen`).
  ![](https://github.com/agoraxyz/guild.xyz/assets/95955389/22eceae3-a080-4ae2-8d17-b42feb1e92f9)
- Connect Discord account.
- Go to the Nation3 Discord Server.

### Expected Behavior

The user's Discord roles should be updated to reflect those at https://guild.xyz/nation3

**Comment by Aasif1234** [comment]
How solve bug

**Comment by Aasif1234** [comment]
How get role
