### ISSUE TITLE
Discord API integration not working

### ISSUE THREAD

**Issue by tklindt** [agoraxyz/guild.xyz#866]
### Describe the bug

Users are getting a `This interaction failed` error when clicking the Join button in a Discord Server. I have tried from several different servers and all of them have this issue. 

![Screen Shot 2023-08-07 at 11 51 52 AM](https://github.com/agoraxyz/guild.xyz/assets/83377811/4bd89e1a-9e32-4750-af73-8b4590ebe27a)

I also tried sending a new Join Button from Guild.xyz as well as using the `/join-button` command in Discord and am getting errors as well.

![Screen Shot 2023-08-07 at 11 52 06 AM](https://github.com/agoraxyz/guild.xyz/assets/83377811/02c47177-b2e1-4dc2-b4ac-3f04d70ef1b6)
![Screen Shot 2023-08-07 at 11 52 40 AM](https://github.com/agoraxyz/guild.xyz/assets/83377811/7f0d8d8a-1093-49fb-91db-aa8e4064e226)

Guild creation also not working for Discord. The bot and app is added to the Discord server but then the window is closed after adding the bot, the button changes back to "Add bot"

### To Reproduce

Visit 'Guild.xyz' Discord Server, in welcome channel click 'Join Our Guild' button. Error will display

### Expected Behavior

`This interaction failed` error will display.

### Which browser are you using? (if relevant)

Chrome / Discord App

**Comment by BrickheadJohnny** [comment]
Hello @tklindt, thank you for the detailed report! Our Discord bot was temporarily offline, but it's up and running again, so you shouldn't experience these issues anymore!

**Comment by tklindt** [comment]
Thank you so much!

**Comment by tklindt** [comment]
Everything working now.

**Comment by tklindt** [comment]
Everything working now!
